# Created by: Nasseef Abukamail
# This Makefile will run tests for the book class
# The tests will run automatically on Travis-CI.
# This is to test continuous integration (CI).
#
#Variables
CC = g++
CFLAGS = -g -Wall -std=c++11

# Linking all the files and run the tests. Use your own header and
# object files.

a.out: book.o book.h book-main.o
	$(CC) $(CFLAGS) _TEST/book.o _TEST/book-main.o -o a.out

book.o: book.cc book.h
	$(CC) -c $(CFLAGS) book.cc -o _TEST/book.o

book-main.o: book-main.cc book.h
	$(CC) -c $(CFLAGS) book-main.cc -o _TEST/book-main.o

######################################### R U N   T E S T s ##################################################
run_tests: book.h book.o
	head book.cc
	$(CC) $(CFLAGS) _TEST/TEST_cases.cc _TEST/book.o -o _TEST/run_tests && ./_TEST/run_tests -sr compact
##############################################################################################################

clean:
	rm -rf _TEST/*.o _TEST/run_tests a.out